source $HOME/.config/nvim/plugins.vim
source $HOME/.config/nvim/basics.vim
source $HOME/.config/nvim/remaps.vim
source $HOME/.config/nvim/functions.vim
source $HOME/.config/nvim/languages.vim
source $HOME/.config/nvim/colors.vim
source $HOME/.config/nvim/gui.vim
source $HOME/.config/nvim/spaces.vim
source $HOME/.config/nvim/prettier.vim
source $HOME/.config/nvim/statusline.vim
